# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vinipay

  adminer:
    image: adminer
    ports:
      - 8080:8080
